// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.DataModel;

namespace Shop.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20191013122112_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.DataModel.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68);

                    b.Property<string>("CategoryDescription");

                    b.Property<string>("CategoryIcon")
                        .HasMaxLength(20);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("CategoryParentId")
                        .HasMaxLength(68);

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryParentId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Shop.DataModel.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68);

                    b.Property<string>("CategoryId")
                        .HasMaxLength(68);

                    b.Property<string>("Images")
                        .HasMaxLength(100);

                    b.Property<string>("ProductDescription");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<double>("ProductPrice");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Shop.DataModel.Category", b =>
                {
                    b.HasOne("Shop.DataModel.Category", "CategoryParent")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryParentId");
                });

            modelBuilder.Entity("Shop.DataModel.Product", b =>
                {
                    b.HasOne("Shop.DataModel.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
